### ISSUE TITLE
Requirements for this repository

### ISSUE THREAD

**Issue by JosephKKim** [zhujiapeng/LowRankGAN#5]
Hello thanks for providing source code for your awesome work!! 
Since there's no requirements.txt file, and I am not familiar with tensorflow I am having hard time making the environment for this repository
Can you specify version and requirements for this work? 

Thanks in advance !

**Comment by zhujiapeng** [comment]
The environment for this repo is the same as the official [stylegan2](https://github.com/NVlabs/stylegan2) tensorflow implementation.

**Comment by JosephKKim** [comment]
Thank you so much for the quick reply! :)
