### ISSUE TITLE
Time for computing Jacobian

### ISSUE THREAD

**Issue by JosephKKim** [zhujiapeng/LowRankGAN#6]
What kind of GPU and environment did you used for computing Jacobian? 
I seems like it won't end till I die...
I just want to see the feasibility..

Thanks, 
Joseph

**Comment by zhujiapeng** [comment]
Yes, computing Jacobian is a little bit time-consuming. For a 1024x1024 model, it takes one hour per image on a 2080 GPU.

**Comment by JosephKKim** [comment]
Thanks for the fast reply.. 
This issue was due to my impatience.
I see it is working now. 

Joseph
